name:                fryxbots
version:             0.1.0.0
github:              "rcdickerson/fryxbots"
license:             BSD-3-Clause
author:              "Robert Dickerson"
maintainer:          "robdickerson@augustana.edu"
copyright:           "2025 Robert Dickerson"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/rcdickerson/fryxbots#readme>

dependencies:
- base >= 4.7 && < 5
- brick >= 2.8 && < 2.10
- containers
- megaparsec
- random
- text
- vty
- vty-crossplatform

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  fryxbots-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - fryxbots